### ISSUE TITLE
模板文件后缀不能改吗？

### ISSUE THREAD

**Issue by songdun** [1021683053/think-template-art#1]
`file_ext: '.html',`
这个模板文件后缀不能改成`.art`吗？ 我吧这个和试图文件的后缀改了之后报的是找不到模板啊

**Comment by 1021683053** [comment]
这个问题忽略了，你先用后缀html的过两天休假结束，改掉他！

**Comment by 1021683053** [comment]
已修改，小BUG让你等太久了！
